Associate reason with EventsDisallowed mode.
replayio/chromium pull request #296
Opened 2023-01-05 15:30 UTC by kannanvijayan

This changes the signature of AutoDisallowEvents and its uses to associate a string reason.  That reason is currently stored in a global, but we should figure out how to pull it out and dump it into crash reports so we have easy access to it.

Not quite sure how to do that yet.

2023-01-05 18:05 UTC, bhackett1024 requested changes
This is a good idea, but we'll want this information in more places than just crash reports, e.g. warnings due to events being disallowed etc.  I think we should modify the RecordReplayBeginDisallowEvents API to take a reason string, and then the recorder can keep track of this internally for all the reporting needs it has.  This will require modifying all our applications which use this API, an alternative would be to add a variant API that takes the reason argument but that adds clutter.

2023-01-06 01:50 UTC, kannanvijayan commented
@bhackett1024 what if we add a new hook to allow the runtime to register a function that lets the driver/linker pull the current disallow-events reason string when it needs?

e.g.
`RecordReplayRegisterEventsDisallowedReasonGetter(const char* (*getter)());`

2023-01-06 12:48 UTC, bhackett1024 commented
> @bhackett1024 what if we add a new hook to allow the runtime to register a function that lets the driver/linker pull the current disallow-events reason string when it needs?
> 
> e.g. `RecordReplayRegisterEventsDisallowedReasonGetter(const char* (*getter)());`

This seems a little circuitous, why don't we add a RecordReplayBeginDisallowEventsWithName API?  Looking through the API we actually did something like this recently, and have both RecordReplayRegisterPointer and RecordReplayRegisterPointerWithName APIs.

2023-01-20 15:21 UTC, bhackett1024 approved these changes

2023-01-20 15:21 UTC, bhackett1024 commented on base/record_replay.h
>    AutoDisallowEvents() { BeginDisallowEvents(); }
Can we remove this constructor?  It seems like we'll always want to have a label.

2023-01-20 19:27 UTC, merged