RUN-1680: wrap `Pause_getAllFrames` in try/catch to stop cross-origin errors to cause crashes
replayio/chromium pull request #521
Opened 2023-04-07 16:29 UTC by Domiii

* https://linear.app/replay/issue/RUN-1680#comment-ac407129

2023-04-07 17:13 UTC, bhackett1024 requested changes
This seems like the wrong fix, and basically rolls back @klochek 's work to surface these JS exceptions as crashes.  Can we try fixing this within V8 so the exception doesn't get thrown, and clients don't get incorrect stacks?

2023-04-08 10:09 UTC, Domiii commented
@bhackett1024 
> This seems like the wrong fix

I would not call it a "wrong fix". Its a "let's quickly get rid of these crashes" type of fix, which is much in line with our previous strategy. I am not at all opposed to spending more time on this and make it better, and I will!

However, I don't agree with the word "wrong" 😊

2023-04-08 16:48 UTC, Domiii commented on third_party/blink/renderer/bindings/core/v8/record_replay_interface.cc
> +  if (node.nodeName == "IFRAME" && node.contentDocument) {
I stumbled across this by accident. This should fix `RUN-1682`.

2023-04-09 10:58 UTC, bhackett1024 approved these changes

2023-04-09 10:58 UTC, bhackett1024 commented on base/record_replay.h
> +bool AllowCrossDomainAccesses();
If we're making this part of the recordreplay API let's use the IsInReplayCode() name from RUN-1502, this name is too specific to the bindings code.

2023-04-09 13:04 UTC, merged