wip: add metabase run to build pipeline
replayio/chromium pull request #894
Opened 2023-09-08 05:14 UTC by ryanjduffy

2023-09-09 00:22 UTC, jazzdan requested changes

2023-09-09 00:22 UTC, jazzdan commented on .buildkite/pipeline.yml
> +    if: build.branch = master
`==`?

2023-09-09 03:52 UTC, ryanjduffy commented on .buildkite/pipeline.yml
> +    if: build.branch = master
Probably?

2023-09-11 19:18 UTC, jazzdan approved these changes

2023-09-11 19:19 UTC, merged